spring:
  application:
    name: TaoXiBlog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taoblog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: taoblog
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000ms
  mail:
    host: smtp.gmail.com
    port: 465
    username: taoxierer@gmail.com
    password: rntdljggztcshvql
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
          ssl:
            enable: true
server:
  port: 8090
blog:
  name: Taoxier's Blog
  api: http://localhost:${server.port}
  cms: http://localhost:8080
  view: http://localhost:8081

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    top.naccl: debug
  file: blog-api/log/blog-dev

mybatis-plus:
  type-aliases-package: com.taoxier.taoxiblog.model.entity
  global-config:
    db-config:
      page-enable: false  # 禁用 MyBatis-Plus 自带的分页功能
      id-type: auto

token:
  expireTime: 259200000 #2.5天
  secretKey: abcdefghijklmnopqrstuvwxyz

comment:
  notify:
    channel: mail
  default-open: true

tg:
  bot:
    api: https://api.telegram.org/bot
    token: 1234567890:qwertyuiopasdfghjklzxcvbnm
    chat-id: 1234567890
    use-proxy: false
    use-reverse-proxy: true
    reverse-proxy-url: https://tg-api-open.naccl.workers.dev

http:
  proxy:
    server:
      host: 127.0.0.1
      port: 7890
      timeout: 10000
upload:
  channel: local
  file:
    path: /Users/taoxier/Desktop/upload/
    access-path: /image/**
    resources-locations: file:${upload.file.path}
  github:
    token: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    username: taoxier
    repos: test
    repos-path: /comment/avatar
#  upyun:
#    bucket-name: nblog
#    username: naccl
#    password: xxxxxxxxxxxxxxxxxxxxxxxx
#    path: /comment/avatar
#    domain: https://cdn.example.com